// src/routes/(app)/project/[id]/revise/ResponseCard.svelte
<script lang="ts">
  import { useChat } from "$lib/use-chat.svelte";
  import { LoaderCircleIcon, RefreshCwIcon, XIcon } from "lucide-svelte";
  import { Card, CardContent, CardHeader } from "@/components/ui/card";
  import { Label } from "@/components/ui/label";
  import { Badge } from "@/components/ui/badge";
  import { useDb } from "@/database/client";
  import { eq } from "drizzle-orm";
  import {
    type Model,
    modelTable,
    type ResponseMessage,
    responseTable,
    type Service,
  } from "@/database/schema";
  import { store } from "@/lib/store.svelte";
  import { updateResponsePrompt } from "../$data";
  import { removeResponse, type ResponsesView, updateMessages } from "./$data.svelte";
  import { invalidateModel } from "@/database";
  import MessageMarkdown from "./MessageMarkdown.svelte";
  import { toast } from "svelte-french-toast";
  import { untrack } from "svelte";

  type Props = {
    response: ResponsesView[number] & { model: Model | null };
    initialMessages: ResponseMessage[];
    service: Service | null;
  };
  let { response, initialMessages, service }: Props = $props();

  let format = $state("markdown");
  let id = $derived(response.id);
  let done = $state(false);
  let body = $state({
    providerId: service?.providerId,
    modelName: response.model?.name,
    baseURL: service?.baseURL,
    apiKey: service?.apiKey,
  });

  $effect(() => {
    Object.assign(body, {
      providerId: service?.providerId,
      modelName: response.model?.name,
      baseURL: service?.baseURL,
      apiKey: service?.apiKey,
    });
  });

  let chat = useChat({
    // @ts-expect-error createdAt type mismatch
    initialMessages,
    body,
    onError: (e) => {
      console.log("onError", e);
      toast.error(e.message);
    },
    onFinish: (message) => {
      console.log("onFinish", chat.messages, message);
      updateMessages(response.id, chat.messages);
    },
  });

  let content = $derived(chat.messages.find((m) => m.role === "assistant")?.content || "");
  let lastMessageIsAssistant = $derived(chat.messages.findLast((m) => m.role === "assistant"));

  // reset done when id changes
  $effect(() => {
    id;
    untrack(() => {
      // reset done when id changes
      done = false;
    });
  });

  // request a chat response on first load if last message is not assistant
  $effect(() => {
    if (!lastMessageIsAssistant && response.error == null && !done) {
      done = true;
      untrack(() => {
        console.log("refreshing");
        chat.reload();
      });
    }
  });

  async function refresh() {
    await updateResponsePrompt(response.id);
    if (store.selected.modelId && store.selected.modelId !== response.modelId) {
      // update modelId in response if selected model is valid
      const model = await useDb().query.modelTable.findFirst({
        where: eq(modelTable.id, store.selected.modelId),
        with: {
          service: true,
        },
      });
      if (model) {
        await useDb()
          .update(responseTable)
          .set({ modelId: model.id })
          .where(eq(responseTable.id, response.id));
      }
    }
    await invalidateModel(responseTable, response);
    // @ts-expect-error hack to update messages
    chat.messages = initialMessages;
    await chat.reload();
  }
</script>

<Card>
  <CardHeader class="flex flex-row space-x-2 space-y-0 bg-muted/50 p-2">
    {#if chat.isLoading}
      <LoaderCircleIcon
        onclick={stop}
        size={16}
        class="loading-icon cursor-pointer text-gray-500 hover:bg-accent"
      />
    {:else}
      <RefreshCwIcon
        onclick={refresh}
        size={16}
        class="cursor-pointer text-gray-500 hover:bg-accent"
      />
    {/if}

    <div class="pr-2 text-xs text-gray-500">{response.model?.name || "deleted"}</div>
    <div class="flex-1"></div>
    <Badge onclick={() => (format = "markdown")} variant="outline" class="hover:bg-gray-200"
      >Markdown</Badge
    >
    <Badge onclick={() => (format = "text")} variant="outline" class="hover:bg-gray-200">Text</Badge
    >
    <XIcon
      class="text-gray-500"
      size={16}
      onclick={() => {
        stop();
        removeResponse(response.id);
      }}
    />
  </CardHeader>
  <CardContent class="p-6">
    {#if response.error}
      <Label class="text-red-500">{response.error}</Label>
    {/if}

    {#if format === "markdown"}
      <MessageMarkdown {content} />
    {:else}
      {content}
    {/if}
  </CardContent>
</Card>

// components/response-card.tsx
import { MemoizedReactMarkdown } from "@/components/markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import { CodeBlock } from "@/components/ui/codeblock";
import { useChat } from "ai/react";
import { memo, useEffect, useState } from "react";
import { store } from "@/app/store";
import { LoaderCircleIcon, RefreshCwIcon, XIcon } from "lucide-react";
import { ref, useSnapshot } from "valtio";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Label } from "@/components/ui/label";

const ResponseCard = memo(
  ({ index }: { index: number }) => {
    const response = useSnapshot(store.responses[index]);
    const selected = useSnapshot(store.selected);
    const [initialMessages] = useState(store.responses[index].messages);
    const { messages, reload, isLoading, stop, error } = useChat({
      initialMessages,
      body: {
        providerId: selected.model?.service.providerId,
        modelId: selected.model?.modelId,
        baseURL: selected.model?.service.baseURL,
        apiKey: selected.model?.service.apiKey,
      },
    });

    function refresh() {
      if (selected.model) {
        console.log("Refreshing", selected);
        store.responses[index].modelId = selected.model.modelId;
        store.responses[index].serviceName = selected.model.service.name;
      }
      reload();
    }

    useEffect(() => {
      // request response if last message not assistant and not error
      const lastMessageIsAssistant = messages.findLast(
        (m) => m.role === "assistant"
      );
      if (
        !lastMessageIsAssistant &&
        store.responses[index].error === undefined
      ) {
        refresh();
      }
    }, []);

    // set error when response is not ok
    useEffect(() => {
      if (error) {
        store.responses[index].error = error.message;
      } else {
        store.responses[index].error = undefined;
      }
    }, [error]);

    useEffect(() => {
      store.responses[index].messages = ref(messages);
    }, [messages]);

    return (
      <Card>
        <CardHeader className=" space-y-0 flex flex-row bg-muted/50 p-2">
          {isLoading ? (
            <LoaderCircleIcon
              onClick={stop}
              size={16}
              className="text-gray-500 loading-icon"
            />
          ) : (
            <RefreshCwIcon
              size={16}
              className="text-gray-500"
              onClick={() => refresh()}
            />
          )}
          <div className="flex-1"></div>
          <div className="text-xs text-gray-500 pr-2">{response.modelId}</div>
          <XIcon
            className="text-gray-500"
            size={16}
            onClick={() => {
              store.responses.splice(index, 1);
            }}
          />
        </CardHeader>
        <CardContent className="p-6">
          {response.error && (
            <Label className="text-red-500">
              {store.responses[index].error}
            </Label>
          )}
          {messages
            .filter((m) => m.role === "assistant")
            .map((message, index) => {
              return (
                <MemoizedReactMarkdown
                  key={index}
                  className="prose break-words dark:prose-invert prose-p:leading-relaxed prose-pre:p-0"
                  remarkPlugins={[remarkGfm, remarkMath]}
                  components={{
                    p({ children }) {
                      return <p className="mb-2 last:mb-0">{children}</p>;
                    },
                    code({ node, inline, className, children, ...props }) {
                      if (children.length) {
                        if (children[0] == "▍") {
                          return (
                            <span className="mt-1 cursor-default animate-pulse">
                              ▍
                            </span>
                          );
                        }

                        children[0] = (children[0] as string).replace(
                          "`▍`",
                          "▍"
                        );
                      }

                      const match = /language-(\w+)/.exec(className || "");

                      if (inline) {
                        return (
                          <code className={className} {...props}>
                            {children}
                          </code>
                        );
                      }

                      return (
                        <CodeBlock
                          // key={Math.random()}
                          language={(match && match[1]) || ""}
                          value={String(children).replace(/\n$/, "")}
                          {...props}
                        />
                      );
                    },
                  }}
                >
                  {message.content}
                </MemoizedReactMarkdown>
              );
            })}
        </CardContent>
      </Card>
    );
  },
  (prevProps, nextProps) => prevProps.index === nextProps.index
);

export { ResponseCard };
