// src/routes/(app)/project/[id]/responses/ResponseCard.svelte
<svelte:options runes={false} />

<script lang="ts">
  import { type Message } from "ai/svelte";
  import { LoaderCircleIcon, RefreshCwIcon, XIcon } from "lucide-svelte";
  import { Card, CardContent, CardHeader } from "@/components/ui/card";
  import { Label } from "@/components/ui/label";
  import { useChat } from "@/lib/use-chat";
  import { Badge } from "@/components/ui/badge";
  import { useDb } from "@/database/client";
  import { eq } from "drizzle-orm";
  import { type ResponseMessage, responseTable, type Service } from "@/database/schema";
  import { store } from "@/lib/store.svelte";
  import { updateResponsePrompt } from "../$data";
  import { removeResponse, type ResponsesView, updateMessages } from "./$data";

  export let response: ResponsesView[number];
  export let initialMessages: ResponseMessage[];
  export let service: Service;

  // when loading messages mark finalized as false
  // when loading complete update messages and set finalized to true
  let finalized = true;
  let format = "markdown";

  const { messages, reload, isLoading, stop, error } = useChat({
    // @ts-expect-error createdAt type mismatch
    initialMessages: initialMessages as Message[],
    body: {
      providerId: service.providerId,
      modelId: response.model.name,
      baseURL: service.baseURL,
      apiKey: service.apiKey,
    },
  });

  $: content = $messages.find((m) => m.role === "assistant")?.content || "";

  const lastMessageIsAssistant = $messages.findLast((m) => m.role === "assistant");
  if (!lastMessageIsAssistant && response.error === undefined) {
    refresh();
  }

  $: console.log("content", content);
  // $: console.log("id", response.id, JSON.stringify(response));

  // $: console.log("isLoading", $isLoading);

  async function refresh() {
    await updateResponsePrompt(response.id);
    if (store.selected.modelId && store.selected.modelId !== response.modelId) {
      await useDb()
        .update(responseTable)
        .set({ modelId: store.selected.modelId })
        .where(eq(responseTable.id, response.id));
    }
    await reload();
  }

  $: {
    if ($isLoading) {
      finalized = false;
    }
    if (!finalized && !$isLoading) {
      finalized = true;
      // @ts-expect-error messages type issue
      updateMessages(response.id, $messages);
    }
  }

  // set error when response is not ok
  $: {
    if ($error) {
      response.error = $error.message;
    } else {
      response.error = null;
    }
  }
</script>

<Card>
  <CardHeader class="flex flex-row space-x-2 space-y-0 bg-muted/50 p-2">
    {#if $isLoading}
      <LoaderCircleIcon
        onclick={stop}
        size={16}
        class="loading-icon text-gray-500 hover:bg-accent"
      />
    {:else}
      <RefreshCwIcon onclick={refresh} size={16} class="text-gray-500 hover:bg-accent" />
    {/if}

    <div class="pr-2 text-xs text-gray-500">{response.model.name}</div>
    <div class="flex-1"></div>
    <Badge onclick={() => (format = "markdown")} variant="outline" class="hover:bg-gray-200"
      >Markdown</Badge
    >
    <Badge onclick={() => (format = "text")} variant="outline" class="hover:bg-gray-200">Text</Badge
    >
    <XIcon class="text-gray-500" size={16} onclick={() => removeResponse(response.id)} />
  </CardHeader>
  <CardContent class="p-6">
    {#if response.error}
      <Label class="text-red-500">{response.error}</Label>
    {/if}

    <!--{#if format === "markdown"}-->
    <!--  <MessageMarkdown {message} />-->
    <!--{:else}-->
    <!--  -->
    <!--{/if}-->
    {content}
  </CardContent>
</Card>

// components/response-card.tsx
import { MemoizedReactMarkdown } from "@/components/markdown";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import { CodeBlock } from "@/components/ui/codeblock";
import { useChat } from "ai/react";
import { memo, useEffect, useState } from "react";
import { store } from "@/app/store";
import { LoaderCircleIcon, RefreshCwIcon, XIcon } from "lucide-react";
import { ref, useSnapshot } from "valtio";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Label } from "@/components/ui/label";

const ResponseCard = memo(
  ({ index }: { index: number }) => {
    const response = useSnapshot(store.responses[index]);
    const selected = useSnapshot(store.selected);
    const [initialMessages] = useState(store.responses[index].messages);
    const { messages, reload, isLoading, stop, error } = useChat({
      initialMessages,
      body: {
        providerId: selected.model?.service.providerId,
        modelId: selected.model?.modelId,
        baseURL: selected.model?.service.baseURL,
        apiKey: selected.model?.service.apiKey,
      },
    });

    function refresh() {
      if (selected.model) {
        console.log("Refreshing", selected);
        store.responses[index].modelId = selected.model.modelId;
        store.responses[index].serviceName = selected.model.service.name;
      }
      reload();
    }

    useEffect(() => {
      // request response if last message not assistant and not error
      const lastMessageIsAssistant = messages.findLast(
        (m) => m.role === "assistant"
      );
      if (
        !lastMessageIsAssistant &&
        store.responses[index].error === undefined
      ) {
        refresh();
      }
    }, []);

    // set error when response is not ok
    useEffect(() => {
      if (error) {
        store.responses[index].error = error.message;
      } else {
        store.responses[index].error = undefined;
      }
    }, [error]);

    useEffect(() => {
      store.responses[index].messages = ref(messages);
    }, [messages]);

    return (
      <Card>
        <CardHeader className=" space-y-0 flex flex-row bg-muted/50 p-2">
          {isLoading ? (
            <LoaderCircleIcon
              onClick={stop}
              size={16}
              className="text-gray-500 loading-icon"
            />
          ) : (
            <RefreshCwIcon
              size={16}
              className="text-gray-500"
              onClick={() => refresh()}
            />
          )}
          <div className="flex-1"></div>
          <div className="text-xs text-gray-500 pr-2">{response.modelId}</div>
          <XIcon
            className="text-gray-500"
            size={16}
            onClick={() => {
              store.responses.splice(index, 1);
            }}
          />
        </CardHeader>
        <CardContent className="p-6">
          {response.error && (
            <Label className="text-red-500">
              {store.responses[index].error}
            </Label>
          )}
          {messages
            .filter((m) => m.role === "assistant")
            .map((message, index) => {
              return (
                <MemoizedReactMarkdown
                  key={index}
                  className="prose break-words dark:prose-invert prose-p:leading-relaxed prose-pre:p-0"
                  remarkPlugins={[remarkGfm, remarkMath]}
                  components={{
                    p({ children }) {
                      return <p className="mb-2 last:mb-0">{children}</p>;
                    },
                    code({ node, inline, className, children, ...props }) {
                      if (children.length) {
                        if (children[0] == "▍") {
                          return (
                            <span className="mt-1 cursor-default animate-pulse">
                              ▍
                            </span>
                          );
                        }

                        children[0] = (children[0] as string).replace(
                          "`▍`",
                          "▍"
                        );
                      }

                      const match = /language-(\w+)/.exec(className || "");

                      if (inline) {
                        return (
                          <code className={className} {...props}>
                            {children}
                          </code>
                        );
                      }

                      return (
                        <CodeBlock
                          // key={Math.random()}
                          language={(match && match[1]) || ""}
                          value={String(children).replace(/\n$/, "")}
                          {...props}
                        />
                      );
                    },
                  }}
                >
                  {message.content}
                </MemoizedReactMarkdown>
              );
            })}
        </CardContent>
      </Card>
    );
  },
  (prevProps, nextProps) => prevProps.index === nextProps.index
);

export { ResponseCard };
