// components/header.tsx
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
} from "@/components/ui/breadcrumb";
import { Button } from "@/components/ui/button";
import { store, submitPrompt } from "@/app/store";
import { useSnapshot } from "valtio";
import { ModelConfig } from "@/components/model-config";
import { SelectModel } from "@/components/select-model";

export function Header() {
  const selected = useSnapshot(store.selected);

  return (
    <header className="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
      <nav aria-label="breadcrumb" className="hidden md:flex">
        <Breadcrumb>
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink href="/">Home</BreadcrumbLink>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
      </nav>
      <div className="relative ml-auto flex-1 md:grow-0">
        <div className="flex flex-row">
          <SelectModel />
          <ModelConfig />
        </div>
      </div>
      {selected.model && <Button onClick={() => submitPrompt()}>Run</Button>}
    </header>
  );
}

// src/routes/project/Header.svelte
<script lang="ts">
  import {
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbList,
  } from "@/components/ui/breadcrumb";
  import { Button } from "@/components/ui/button";
  import { type Model, type Project, store, submitPrompt } from "@/store.svelte";
  import ModelConfig from "@/components/model-config/ModelConfig.svelte";
  import SelectModel from "@/routes/project/SelectModel.svelte";
  import { PlayIcon } from "lucide-svelte";
  import Sheet from "@/components/Sheet.svelte";

  type Props = {
    project: Project;
  };
  let { project }: Props = $props();
</script>

<header
  class="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6 sm:pt-2"
>
  <Sheet />
  <nav aria-label="breadcrumb" class="hidden md:flex">
    <!--    <Breadcrumb>-->
    <!--      <BreadcrumbList>-->
    <!--        <BreadcrumbItem>-->
    <!--          <BreadcrumbLink href="/">Home</BreadcrumbLink>-->
    <!--        </BreadcrumbItem>-->
    <!--      </BreadcrumbList>-->
    <!--    </Breadcrumb>-->
  </nav>
  <div class="relative ml-auto flex-1 md:grow-0">
    <div class="flex flex-row">
      <SelectModel />
      <ModelConfig />
    </div>
  </div>

  {#if store.selected.modelId}
    <Button onclick={() => submitPrompt(project)}>
      <PlayIcon size={16} class="mr-2" />
      Run
      <div
        class="w-13 pointer-events-none ml-1 hidden h-6 rounded-full bg-white bg-opacity-20 px-2 py-1 md:inline-flex"
      >
        <div class="pointer-events-none text-center text-xs font-light text-white">Ctrl + ⏎</div>
      </div>
    </Button>
  {/if}
</header>
